UNAME := $(shell uname)

AS	= x86_64-elf-as --32
LD	= x86_64-elf-ld
LDFLAGS = -m elf_i386
CC	= x86_64-elf-gcc -march=i386
CFLAGS  = -gdwarf-2 -g3 -m32 -fno-builtin -fno-stack-protector -fomit-frame-pointer -fstrength-reduce

CPP	= x86_64-elf-cpp -nostdinc
AR	= x86_64-elf-ar
STRIP = x86_64-elf-strip
OBJCOPY = x86_64-elf-objcopy